### ISSUE TITLE
NotADirectoryError: [WinError 267]

### ISSUE THREAD

**Issue by sniperc96** [divanoLetto/3D_STEP_Classification#2]
Hello, when I run step_2_graph.py, a reported error has occurred.

Here are the reported errors：
Traceback (most recent call last):
  **File "D:/STEP-research/3D_STEP_Classification-main/Graph_classification/Graph_convertion/step_2_graph.py", line 29, in <module>
    make_graphh_dataset(path_stp, path_graph)
  File "D:/STEP-research/3D_STEP_Classification-main/Graph_classification/Graph_convertion/step_2_graph.py", line 16, in make_graphh_dataset for file in os.listdir(path_stp + dir + "/"):
NotADirectoryError: [WinError 267] 目录名称无效。: 'D:/STEP-research/3D_STEP_Classification-main/data/Traceparts/STEP_models/Class 0/0_2.stp/'**

I don't know how to solve this problem, can you give me advice please? Thanks!

**Comment by sniperc96** [comment]
> Hello, when I run step_2_graph.py, a reported error has occurred.
> 
> Here are the reported errors： Traceback (most recent call last): **File "D:/STEP-research/3D_STEP_Classification-main/Graph_classification/Graph_convertion/step_2_graph.py", line 29, in make_graphh_dataset(path_stp, path_graph) File "D:/STEP-research/3D_STEP_Classification-main/Graph_classification/Graph_convertion/step_2_graph.py", line 16, in make_graphh_dataset for file in os.listdir(path_stp + dir + "/"): NotADirectoryError: [WinError 267] 目录名称无效。: 'D:/STEP-research/3D_STEP_Classification-main/data/Traceparts/STEP_models/Class 0/0_2.stp/'**
> 
> I don't know how to solve this problem, can you give me advice please? Thanks!

I found this to be a stupid mistake because I was using the wrong path_stp.

Change path_stp to D:/STEP-research/3D_STEP_Classification-main/data/Traceparts/STEP_models, remove Class 0 and it runs successfully

I'm sorry to bother you.
